---
services:
    transformers-notebook:
        build: ./
        ports:
          - 8000:8888
        environment:
            - JUPYTER_TOKEN=asoom 
        volumes:
            - ./:/home/jovyan    
...